
create database formDB;

use formDB

CREATE TABLE formDB(
SCActEnd varchar(50),
5BProtocolNumber varchar(50),
1CUseEquip boolean default false,
VAnimals boolean default false,
StudentName4 varchar(50),
SCContinue1 boolean default false,
SCContinue0 boolean default false,
1BStudentPrinted varchar(50),
QSSuper1 boolean default false,
HSAS varchar(50),
QSSuper0 boolean default false,
StudentsName varchar(50),
HSIRBPrinted3 varchar(50),
HSIRBPrinted2 varchar(50),
1ASchoolAdd2 varchar(50),
HSIRBPrinted1 varchar(50),
1ASchoolAdd1 varchar(50),
6BTissuesObtained varchar(50),
1CGroupExp varchar(50),
5aDSreview boolean default false,
SCNonPhone2 varchar(50),
6aSRCIACUC boolean default false,
SCNonPhone1 varchar(50),
70708Chg varchar(50),
parentalno boolean default false,
1CGroupExp1 boolean default false,
QSyes boolean default false,
6BFresh boolean default false,
1CSAPrinted varchar(50),
CFParticipantPrinted varchar(50),
6AQSStudentTraining varchar(50),
70809Chg varchar(50),
Vcare boolean default false,
Vertebrates boolean default false,
rDNA boolean default false,
CFConfidentiality1 varchar(50),
1BParentName varchar(50),
StudentChecklist boolean default false,
parentalyes boolean default false,
Vapprovaldate varchar(50),
Humans boolean default false,
6BOrgan boolean default false,
6BQSEmail varchar(50),
SRCChair5adate varchar(50),
1BStateSRCChairDate varchar(50),
SCNonName1 varchar(50),
ProjectTitle5 varchar(50),
SCNonName2 varchar(50),
6BQSInstitution varchar(50),
5BSpeciesUsed varchar(50),
ASPrinted varchar(50),
TeamMember2 varchar(50),
6AConcur0 boolean default false,
TeamMember3 varchar(50),
6AConcur1 boolean default false,
SCResPlan boolean default false,
ResearchInst boolean default false,
5BTissueUse1 boolean default false,
5BTissueUse0 boolean default false,
SCAbstract boolean default false,
6absl2date varchar(50),
ParentalNA boolean default false,
notapproved boolean default false,
70809Theme varchar(50),
6aiacucdate varchar(50),
VT5B boolean default false,
VT5A boolean default false,
CF7 boolean default false,
7SigDate varchar(50),
70809Title varchar(50),
6anoapprovalrequired boolean default false,
ApprovalForm boolean default false,
ASPhone varchar(50),
RAQSReviewDate varchar(50),
70708Title varchar(50),
6bqsdate varchar(50),
5bqspidate varchar(50),
QSWhoSuper varchar(50),
RAQSPrinted varchar(50),
SCActStart varchar(50),
RADisposal varchar(50),
DSrequired boolean default false,
QSHumans0 boolean default false,
QSHumans1 boolean default false,
ASEmail varchar(50),
7CurrChg varchar(50),
Projectapproved boolean default false,
1CSATitle varchar(50),
HSIRBDATE varchar(50),
6BQSTitle varchar(50),
5adsdate varchar(50),
6asrcapproval varchar(50),
CFPurpose varchar(50),
VTQS boolean default false,
1ASchool varchar(50),
18no boolean default false,
6BInstitutionObtained varchar(50),
writtenminorassentyes boolean default false,
QSSuperTraining varchar(50),
1CSAEmail varchar(50),
5ADSEmail varchar(50),
CFParentAssentPrinted varchar(50),
70809Var varchar(50),
Microorganisms boolean default false,
18yes boolean default false,
AdultSponsorChecklist boolean default false,
5AVetEmail varchar(50),
6BHuman boolean default false,
1CRulesReview1 boolean default false,
1CRulesReview0 boolean default false,
WorkedWithStudent boolean default false,
1CSubset1 boolean default false,
1AASEmail varchar(50),
1BStateSRCChairPrinted varchar(50),
RASafety varchar(50),
1CSubset0 boolean default false,
SCResInst boolean default false,
CFAdultAssentDate varchar(50),
6boshealthact boolean default false,
5AVetPrinted varchar(50),
RAQSPosition varchar(50),
1AGrade varchar(50),
HazRisk boolean default false,
SCOther boolean default false,
5ACommonName varchar(50),
LegalInstrument boolean default false,
70708Theme varchar(50),
Vcertdoses boolean default false,
5aDAcert boolean default false,
AllProjectItems boolean default false,
1CCreative varchar(50),
7CurrVar varchar(50),
6aSRCbsl2 boolean default false,
PotHaz boolean default false,
1BSRCChairAppDate varchar(50),
7CurrObj varchar(50),
6AMinimizeRisk varchar(50),
SampleInformedConsent boolean default false,
PHRisk boolean default false,
Tissues boolean default false,
6ADisposal varchar(50),
Minimalrisk boolean default false,
5ADSPrinted varchar(50),
SCNonAdd1B varchar(50),
QSPosition varchar(50),
SCNonAdd1A varchar(50),
6aSRCChairPrintedName varchar(50),
1CSpecificProcs varchar(50),
ApprovalDate varchar(50),
ContinForm boolean default false,
1APhone varchar(50),
CFParentAssentDate varchar(50),
QualSciForm boolean default false,
6AConcurExp varchar(50),
HSIRB2date varchar(50),
5AHousing varchar(50),
QSRuleReview1 boolean default false,
QSRuleReview0 boolean default false,
QSDSEmail varchar(50),
6BQSPrinted varchar(50),
18NA boolean default false,
CFAskedTo1 varchar(50),
VDSQSRequired boolean default false,
QSName varchar(50),
QSDSTraining varchar(50),
6bqstissuesverify boolean default false,
70708Var varchar(50),
CFASEmail varchar(50),
6ASite varchar(50),
ProjectTitle2 varchar(50),
QSDSApprovalDate varchar(50),
IncHumans boolean default false,
RAIDHazards varchar(50),
QSVert1 boolean default false,
70708Obj varchar(50),
QSVert0 boolean default false,
1BSRCChairPrinted varchar(50),
5BQSPIPrintedName varchar(50),
HSSubmitResPlan boolean default false,
QSDSPhone varchar(50),
RAQSEmail varchar(50),
1CGetIdea varchar(50),
minorassentNA boolean default false,
5ASRCChairPrinted varchar(50),
5BStudentrole varchar(50),
1BDateAck varchar(50),
1AAdultSpon varchar(50),
HazQS boolean default false,
QSSubset1 boolean default false,
QSSubset0 boolean default false,
HSIRBDegree3 varchar(50),
HSIRBDegree2 varchar(50),
SCNonAdd2A varchar(50),
HSIRBDegree1 varchar(50),
HumanSub boolean default false,
SCNonAdd2B varchar(50),
QSInstitution varchar(50),
6BPrimary boolean default false,
70809Obj varchar(50),
1BSRCIRBAppDate varchar(50),
PH6B boolean default false,
CFBenefits varchar(50),
5AAftermath varchar(50),
PH6A boolean default false,
QSDegrees varchar(50),
6asrcbsl1 boolean default false,
1213Ab boolean default false,
qsno boolean default false,
CFRisks1 varchar(50),
ChecklistReview boolean default false,
RAIDAssess varchar(50),
StudentName varchar(50),
1ASchoolPhone varchar(50),
1CPerformExp boolean default false,
6BBlood boolean default false,
5BNumberUse varchar(50),
RAQSTraining varchar(50),
ASDateofReview varchar(50),
1BSRCPrinted varchar(50),
1BDateApp varchar(50),
HSWorkingQS0 boolean default false,
HSWorkingQS1 boolean default false,
ReviewRules boolean default false,
QSHazard1 boolean default false,
QSHazard0 boolean default false,
1AEmail varchar(50),
morethanminimal boolean default false,
6ABiosafetyLevel varchar(50),
6absl1date varchar(50),
7CurrTheme varchar(50),
ResearchPlan boolean default false,
6BBodyFluids boolean default false,
HSIRB3date varchar(50),
QSPrinted varchar(50),
SCSchool boolean default false,
VandDSrequired boolean default false,
1BRegSsRCChairPrinted varchar(50),
QSEducation varchar(50),
QSAddress varchar(50),
Vcert boolean default false,
SCfield boolean default false,
HSAttachSurvey boolean default false,
SCOtherExpl varchar(50),
QSControl1 boolean default false,
QSControl0 boolean default false,
1CSADateSigned varchar(50),
HSASEmail varchar(50),
HAZ boolean default false,
5BLabTraining varchar(50),
CFAdultSponsor varchar(50),
7CurrTitle varchar(50),
1cGroupExp0 boolean default false,
1112Ab boolean default false,
PriorApprovalRequired boolean default false,
CFTimeRequired varchar(50),
ProjectTitle varchar(50),
QSDSPrinted varchar(50),
minorassentno boolean default false,
PHQS boolean default false,
5BDeath varchar(50),
6ABiologicAgents varchar(50),
HSInformedConsentAttached boolean default false,
1ATeamLeader varchar(50),
RAResources varchar(50),
1BSRCChairDate varchar(50),
QSEmail varchar(50),
SCHome boolean default false,
1CSAInstitution varchar(50),
1CSAAddress varchar(50),
primary key(SCActEnd, StudentsName));
